# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arctorna Mónival
email: moni@arctornamonival.hu
description: >- # this means to ignore newlines until "baseurl:"
  Az arc megereszkedése és ráncosodása megelőzhető, vagy visszafordítható az arc
  izmainak rendszeres edzésével. Épp úgy, mint a testen! Amikor az arc izmai
  elkezdenek gyengülni, az arc egyre petyhüdtebbé válik, fáradtabbnak,
  öregebbnek néz ki. Ezt a lassú sorvadási folyamatot azonban képesek vagyunk
  megállítani az arcizmok rendszeres edzésével, ugyanúgy mint a test bármely
  részén. Gondosan összeállított gyakorlatokkal hatékonyan megemelhetjük,
  feszesíthetjük arcunkat, kisimíthatjuk a ráncokat, vagy eltüntethetjük a
  tokát.
baseurl: "/arctorna" # the subpath of your site, e.g. /blog
url: "https://arctornamonival.hu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
lang: hu

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
