# Site settings
# -------------
title: Arctorna Mónival
email: moni@arctornamonival.hu
description: >-
  Arcfiatalítás természetesen
url: "https://arctornamonival.hu"
lang: hu
timezone: Europe/Budapest
google_analytics: UA-124177462-1

relative_links:
  enabled:     true
  collections: false

facebook_username: arctornamonival

# Default front matter
# --------------------
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/supergroup-square.jpg

# Build settings
# --------------
markdown: kramdown
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
