registration_link: https://arctornaworkshop.typeform.com/to/N9N1Sb
address: 1032 Budapest, San Marco utca
price: 35000
deposit: 10000
private_price: 70000
price_desc: A 10 alkalmas blokk ára
events:
  - date: 2021-1-25T10:30
    start: "10:30"
    end: "11:30"
    full: false
    title: Kezdő Arctorna Tréning – online, délelőtti&nbsp;1.&nbsp;csoport
    classes:
      -
        day: hétfő
        time: "10:30"
      -
        day: csütörtök
        time: "8:30"
    description: >-
      Az órák hétfőn és csütörtökön délelőtt vannak.
  - date: 2021-1-26T8:30
    start: "8:30"
    end: "9:30"
    full: true
    title: Kezdő Arctorna Tréning – online, délelőtti&nbsp;2.&nbsp;csoport
    classes:
      -
        day: kedd
        time: "8:30"
      -
        day: péntek
        time: "9:00"
    description: >-
      Az órák kedden és pénteken délelőtt vannak.
  - date: 2021-1-25T17:30
    start: "17:30"
    end: "18:30"
    full: true
    title: Kezdő Arctorna Tréning – online, délutáni&nbsp;1.&nbsp;csoport
    classes:
      -
        day: hétfő
        time: "17:30"
      -
        day: csütörtök
        time: "16:30"
    description: >-
      Az órák hétfőn és csütörtökön délután vannak.
  - date: 2021-1-26T17:00
    start: "17:00"
    end: "18:00"
    full: true
    title: Kezdő Arctorna Tréning – online, délutáni&nbsp;2.&nbsp;csoport
    classes:
      -
        day: kedd
        time: "17:00"
      -
        day: péntek
        time: "16:30"
    description: >-
      Az órák kedden és pénteken délután vannak.
