registration_link: https://arctornaworkshop.typeform.com/to/N9N1Sb
address: 1032 Budapest, San Marco utca
price: 35000
deposit: 10000
private_price: 59000
price_desc: A 10 alkalmas blokk ára
events:
  - date: 2020-1-20T09:00
    start: "9:00"
    end: "10:00"
    full: false
    title: Kezdő Arctorna Tréning – délelőtti&nbsp;csoport
    classes:
      -
        day: hétfő
        time: "9:00"
      -
        day: péntek
        time: "11:30"
    description: >-
      Az órák hétfőn és pénteken délelőtt vannak. Ha ez időnként nem lenne
      alkalmas, lehetőség van a délutáni órákon való részvételre.
  - date: 2020-1-21T16:00
    start: "16:00"
    end: "17:00"
    title: Kezdő Arctorna Tréning – délutáni&nbsp;csoport
    classes:
      -
        day: kedd
        time: "16:00"
      -
        day: csütörtök
        time: "17:30"
    description: >-
      Az órák kedden és csütörtökön délután vannak. Ha ez időnként nem lenne
      alkalmas, lehetőség van a délelőtti órákon való részvételre.
