registration_link: https://arctornaworkshop.typeform.com/to/N9N1Sb
address: 1032 Budapest, San Marco utca
price: 35000
deposit: 10000
private_price: 59000
price_desc: A 10 alkalmas blokk ára
events:
  - date: 2019-9-10T09:30
    start: "9:30"
    end: "10:30"
    title: Kezdő Arctorna Tréning
    classes:
      -
        day: kedd
        time: "9:30"
      -
        day: csütörtök
        time: "10:00"
    description: >-
      Az órák kedden és csütörtökön vannak.
