registration_link: https://arctornaworkshop.typeform.com/to/N9N1Sb
address: 1032 Budapest, San Marco utca
price: 35000
deposit: 10000
private_price: 59000
price_desc: A 10 alkalmas blokk ára
events:
  - date: 2019-5-20T012:00
    start: "12:00"
    end: "13:00"
    title: Kezdő Arctorna Tréning
    classes:
      -
        day: hétfő
        time: "12:00"
      -
        day: csütörtök
        time: "10:00"
    description: >-
      Az órák hétfőn és csütörtökön vannak.
